### ISSUE TITLE
base4 for SpecialKey is too bright / too similar to the comments

### ISSUE THREAD

**Issue by vdrandom** [whatyouhide/vim-gotham#16]
As a result, it's a bit confusing: non-printed symbols are mixed with comments since comments too use base4 colour. Even base3 may be a bit too bright, but is still much better.
```diff
diff --git a/colors/gotham.vim b/colors/gotham.vim
index 82ba3de..093b26a 100644
--- a/colors/gotham.vim
+++ b/colors/gotham.vim
@@ -135,7 +135,7 @@ call s:Col('Type', 'orange')
 call s:Col('PreProc', 'red')
 
 " Tildes on the bottom of the page.
-call s:Col('NonText', 'base4')
+call s:Col('NonText', 'base3')
 
 " Concealed stuff.
 call s:Col('Conceal', 'cyan', s:background)
@@ -151,7 +151,7 @@ call s:Col('StatusLineNC', 'base4', 'base2')
 call s:Col('MatchParen', 'base1', 'orange')
 
 " Special keys, e.g. some of the chars in 'listchars'. See ':h listchars'.
-call s:Col('SpecialKey', 'base4')
+call s:Col('SpecialKey', 'base3')
 
 " Folds.
 call s:Col('Folded', 'base6', 'blue')
```
(EDIT: NonText should be edited as well as SpecialKey.)

**Comment by whatyouhide** [comment]
Could you send a PR with before/after screenshot? I'd love that :heart:

**Comment by vdrandom** [comment]
![screenshot - 230115 - 14 52 30](https://cloud.githubusercontent.com/assets/3367071/5874195/9e71c8ac-a30f-11e4-9613-45a3ba667c40.png)
Left to right: base4, base3, base2. Tabs displayed as >------
