### ISSUE TITLE
Search Highlight is kind of unusable with unite.vim

### ISSUE THREAD

**Issue by benjumanji** [whatyouhide/vim-gotham#17]
The only blackspot for me with this theme:

Note that it is almost impossible to actually read the matched term on the first line (the term is `Base` and it's in the blackhole between extends and TimeSeriesSpec). This is a screenshot taken from within unite.vim's grep source, but the same applies to any other searches. It's enough that I am starting to think about departing from the one true batman path, and going with other themes. Thoughts?

**Comment by whatyouhide** [comment]
Hey there @benjumanji, thanks for the report. I'll do what I can to keep you on the Batman path :).

Do you know what is the syntax element on the first line? You should be able to find out with something like http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor. I'm assuming unite.vim's grep source highlights differently than regular vim `/` search. I personally don't use unite.vim or I'd look into this myself.

Sorry for the inconvenience!

**Comment by benjumanji** [comment]
Using the binding that I got from wikia (which I wish I could claim to understand), I have the following: `hi<uniteSource__GrepPattern> trans<uniteSource__GrepPattern> lo<Search>`. I will do a bit more digging, to see where these are set, and maybe we can have something added to the theme. I also have some related problems with oblique (another search plugin), that I will try to do something with as well.

**Comment by benjumanji** [comment]
https://github.com/Shougo/unite.vim/blob/b2ad0860d783730e255ce7d0e1cdcc396fb1d984/autoload/unite/sources/grep.vim#L150

Looks like `g:unite_source_grep_search_word_highlight` is what needs to be set. The question is what color should it be, maestro?

**Comment by benjumanji** [comment]
(forgive me for deleting the screenshot, I'll add another one back for posterity, I just realized that some of the things on display in the search are not supposed to be for public consumption [PII])

**Comment by whatyouhide** [comment]
I suppose the highlighting of the *current* match should be different from the highlighting of the other matches (in the screenshot you posted yesterday). If that's the case, I'd probably go with a green background and a white foreground. If you want to try that, you can either put something like this in your `~/.vimrc`:

```viml
highlight uniteSource__GrepPattern ctermfg=15 ctermbg=2
```

or you can set `g:unite_source_grep_search_word_highlight`:

```viml
let g:unite_source_grep_search_word_highlight = 'ctermfg=15 ctermbg=2'
```

You also can mess with the source of vim-gotham. If you're comfortable with modifying the source of vim-gotham we'd probably solve this more easily, but absolutely don't worry if you're not, we'll try to solve it step by step :).

**PS** I'm assuming you're using terminal vim. If you're using gVim or MacVim, tell me so we can use hex colors instead of base16 ones :).

**Comment by benjumanji** [comment]
The default value is "Search". If I set it to anything else I lose the Yellow / Reverse pattern. Maybe I need to take this up with unite and then come back.

**Comment by benjumanji** [comment]
Awesome! So unfortunately (I guess due to some silliness with arg parsing) setting the variable fails, adding the highlight group works!

![2015-03-09-103219_1257x164_scrot](https://cloud.githubusercontent.com/assets/290429/6553350/c2cdff6c-c647-11e4-930e-8385519c6473.png)

It's maybe a little *too* low contrast on the matched and selected line, but at least it's solvable for me now. I guess it would be nice to have a default so that this works out of the box for all unite users, but having learnt something new about lighlighting (thanks!) I am happy that I can muck about with this to my hearts content.

**Comment by whatyouhide** [comment]
Awesome, super happy to help! I'd like to extend vim-gotham support to unite.vim too but I'd like your advice on this. You tried a green background (`ctermbg=2`). If you can, try some other colours (as values of `ctermbg`) and tell me which one looks better. You can try:

* red: `1`
* orange: `9`
* yellow: `3`
* magenta: `13`
* violet: `5`
* blue: `4`
* cyan: `6`

**Comment by benjumanji** [comment]
Having played around with it over the past couple of days.. green / white (your original suggestion) is my fav.

**Comment by whatyouhide** [comment]
Ok then, just pushed the changes so that it should work with unite.vim out-of-the-box™.

If you could temporarily remove that line from your `~/.vimrc` and try the updated version of the plugin it would be great, so we know it's all smooth. Thanks for the help!

**Comment by benjumanji** [comment]
Have the latest changes, can confirm that it all works just fine.
