### ISSUE TITLE
vim-gotham and gotham-contrib are featured on unix porn !

### ISSUE THREAD

**Issue by alexanderjeurissen** [whatyouhide/vim-gotham#24]
![screen shot 2016-02-06 at 17 16 27](https://cloud.githubusercontent.com/assets/1220084/12869166/6cfc5872-cd17-11e5-870d-300aad786432.png)
I submited my current configuration showcasing my current customized Tmux statusline together with the Gotham colorschemes on the unix porn subredit !!

I hope it helps more people find this awesome colorscheme.

![screen shot 2016-02-06 at 21 16 34](https://cloud.githubusercontent.com/assets/1220084/12869165/5c8dd6fa-cd17-11e5-95a8-5e1fcc16b401.png)

**Comment by whatyouhide** [comment]
:tada: thanks so much for the kind words and for the visibility :yum:
