### ISSUE TITLE
Wrong color for Error and WarningMsg

### ISSUE THREAD

**Issue by cenkalti** [whatyouhide/vim-gotham#27]
I get following pic by running ```:verbose hi``` command. ```Error``` seems wrong for gotham theme.
![screenshot 2016-04-19 23 12 20](https://cloud.githubusercontent.com/assets/661618/14654027/6b43b920-0684-11e6-8e2d-e1d6123938b3.png)

...and ```WarningMsg```: 
![screenshot 2016-04-19 23 14 54](https://cloud.githubusercontent.com/assets/661618/14654061/8fa25c04-0684-11e6-8a0b-4bfe44cea18d.png)

I fixed the problem temporarily by overriding these 2 in my ```init.vim``` file:
![screenshot 2016-04-19 23 17 13](https://cloud.githubusercontent.com/assets/661618/14654139/e93e966a-0684-11e6-8c5e-85ea0e99d050.png)

Should I send a PR?

**Comment by whatyouhide** [comment]
Hey @cenkalti, good catch! Yes, a PR would be very welcome 😺
