### ISSUE TITLE
Please add a color definition for Function group

### ISSUE THREAD

**Issue by shmerl** [whatyouhide/vim-gotham#32]
From `:help group-name`

    Function       function name (also: methods for classes)

Many themes highlight function names differently than default color, making them more visible. Currently vim-gotham doesn't do it because Function definition is missing.

See example with Rust syntax highlighting (note that **fn** which is a keyword and **main** which is a function name are the same color here which doesn't look so well):

![no_function_color](https://cloud.githubusercontent.com/assets/310927/20773799/a42b13f2-b721-11e6-92d7-218448900c58.png)

Example of how it can look better:

![function_color](https://cloud.githubusercontent.com/assets/310927/20774560/e2162078-b724-11e6-8583-d8c0bd6f235f.png)

Sample definition for the color and group:

    let s:colors.sea   = { 'gui': '#4d618e', 'cterm': 4  }
    
    " Function.
    call s:Col('Function', 'sea', s:background)

**Comment by whatyouhide** [comment]
Hey @shmerl, would you be willing to submit a PR for this? I am busy with other work these days 😄

**Comment by shmerl** [comment]
Sure. Are you OK with this color / name, or you have any preference of different color or how to call it? I started with brighter one and called it "sea", but ended up with a bit darker tone which is close to your violet. I can call it "manganese", since its oxides can have such color.

**Comment by whatyouhide** [comment]
I don't think we should add a new color for this in the colorscheme. We can use one of the existing colors though :)

**Comment by whatyouhide** [comment]
Ping @shmerl?

**Comment by shmerl** [comment]
Sorry, I was a bit busy lately. I'll try to wrap it up today.

**Comment by shmerl** [comment]
See https://github.com/whatyouhide/vim-gotham/pull/33

The result isn't the best looking IMO though. I liked the custom color more.

**Comment by whatyouhide** [comment]
Closed by #33.
