### ISSUE TITLE
Functions turned to yacky colors

### ISSUE THREAD

**Issue by sittim** [whatyouhide/vim-gotham#37]
This is the most awesome theme out there, but for some reason, the functions became this yucky color:

![selection_072](https://cloud.githubusercontent.com/assets/8825037/23614990/e79b10d4-0252-11e7-9413-691524f3a05b.png)

Why did it change, is it possible to go back to a little brighter color?

**Comment by whatyouhide** [comment]
Hey @sittim, do you have an example of how it was before? I suppose the change comes from #33 (pinging @shmerl for that :)).

**Comment by sittim** [comment]
Unfortunately I do not have the other color without going back though git, I just remember that its intensity was closer to the other colors.  Its current intensity looks closer to the comments.

**Comment by shmerl** [comment]
I proposed to use a bit different color (to make a new one), but @whatyouhide asked to re-use existing one. [See example here](https://github.com/whatyouhide/vim-gotham/issues/32). The proposed color was brighter.

**Comment by whatyouhide** [comment]
Okay, I see now. The current color looks indeed a bit "outside" the theme, so I'll revert #33 and keep the close colors we had before. Thanks both for the help! 💟

**Comment by sittim** [comment]
Much better, but it would be nice to add a dedicated color to a function as was proposed.  Now the keywords and functions look the same:


![selection_073](https://cloud.githubusercontent.com/assets/8825037/23620783/2a459590-0266-11e7-86c8-d9eeac408c48.png)

By the way, I tried lots of themes, this one is the most pleasant.
