### ISSUE TITLE
base16 request.

### ISSUE THREAD

**Issue by bytebeast** [whatyouhide/vim-gotham#39]
This is more of a request than a bug. I love this theme, but.. I love the consistency of base16. Can you guys port this over to base16-shell? This would require base16-shell, base16-vim, vim-airline-themes changes, if you do.

**Comment by whatyouhide** [comment]
I do not have time to do this, sorry :(. Contributions are more than welcome though, so if you want to give it a try, I would be happy to review :)

**Comment by whatyouhide** [comment]
I'm gonna close this one @bytebeast as there was no contribution on it. Feel free to open a PR if you put something together :)

**Comment by blockloop** [comment]
Here's one I just made. Feel free to contribute it or steal it or whatever.

```
scheme: "Gotham"
author: "Brett Jones (https://blockloop.io)"
base00: "0c1014"
base01: "11151c"
base02: "091f2e"
base03: "0a3749"
base04: "245361"
base05: "599cab"
base06: "99d1ce"
base07: "d3ebe9"
base08: "c23127"
base09: "d26937"
base0A: "edb443"
base0B: "33859E"
base0C: "2aa889"
base0D: "195466"
base0E: "888ca6"
base0F: "4e5166"
```

**Comment by sboysel** [comment]
Thanks @whatyouhide  and @blockloop .  I packaged the above scheme in [sboysel/base16-gotham-scheme](https://github.com/sboysel/base16-gotham-scheme).  Let me know if there is any issue with the attribution.
