### ISSUE TITLE
Airline gotham256 not working

### ISSUE THREAD

**Issue by islam-taha** [whatyouhide/vim-gotham#41]
gotham256 not autoloaded on startup, and when force replacing airline theme with `AirlineTheme gotham256` the following errors appear:

<img width="1489" alt="screen shot 2017-05-14 at 3 11 16 pm" src="https://cloud.githubusercontent.com/assets/11490365/26034125/ebe16990-38b7-11e7-866c-dd26bfec66e4.png">

Any help would be appreciated!
thanks

**Comment by whatyouhide** [comment]
Hey @islam-taha, thanks for the report.

Could you have a look at #35 and check out if they're related?

**Comment by islam-taha** [comment]
I've already seen it, they are not related except in not autoloading, but there is no error arising from calling the airline theme.

**Comment by whatyouhide** [comment]
@islam-taha do you still have this problem? I don't use vim anymore. If you have this problem, do you mind giving fixing it a shot? Otherwise let me know and I'll close this issue for inactivity. Thanks! 💟

**Comment by whatyouhide** [comment]
Closing this issue for now, @islam-taha feel free to reopen if you still have this issue. Thanks all!
