### ISSUE TITLE
Normal gotham didn't look dark as the 256 version on Iterm2

### ISSUE THREAD

**Issue by voodoomsr** [whatyouhide/vim-gotham#42]
Hi guys, I've applied the gotham colorscheme but for some reason it looks with a grey background and orange keywords along with some other pale colors. That's not how it is supposed to be, when I changed it to the 256 version it looks great, so I don't know what makes the normal version looks like that.

I've download the last version from the site and manually putted in ~/.vim/colors folder.
I see this problem only when I use iTerm2 as the terminal. In the default terminal looks fine.

pd: Even when the 256 versions looks something better, there are a lot of difference to what you showed in the screenshot. That screenshot looks awesome, and is nowhere near it how it looks my terminal. Is it that normal? do I need to change something else?

More tests (normal version not 256):
On default terminal looks dark, but lot of colors are not correct.
On Iterm2 looks bad, greyed pale colors.
On MacVim looks awesome, how it should be on on my terminal.

**Comment by whatyouhide** [comment]
@voodoomsr are you using the proper colorscheme for your terminal as per https://github.com/whatyouhide/gotham-contrib?

**Comment by whatyouhide** [comment]
Closing this since no answer. Feel free to reopen if necessary 💟
