### ISSUE TITLE
Strange cursor color over brackets.

### ISSUE THREAD

**Issue by dimascyriaco** [whatyouhide/vim-gotham#44]
That's a weird behavior. I hope i can explain it clearly.

When the cursor goes over a bracket character the character becomes orange with dark background, and the matching character becomes dark with orange background. It make it looks like the cursor have jumped to the matching character. It's very disorienting.

Maybe some screenshots will help.

![gothan-cursor-before](https://user-images.githubusercontent.com/65256/31135591-d8678d42-a83b-11e7-91c9-02eb0ca0eddd.png)
![gothan-cursor-over](https://user-images.githubusercontent.com/65256/31135598-dcb1d6c8-a83b-11e7-9eef-f156c1655fc8.png)
![gothan-cursor-after](https://user-images.githubusercontent.com/65256/31135603-e056e03e-a83b-11e7-83a6-d836f371e700.png)

**Comment by whatyouhide** [comment]
Hey @dimascyriaco, thanks for the report.

I am not using vim currently and I don't have time to look deeply into this. Would you mind investigating what combination of colors is causing this? I suspect it has to do with the block cursor inverting the colors or something like that.

**Comment by fcobos** [comment]
Seems to be this

```
" Matching parenthesis.
call s:Col('MatchParen', 'base1', 'orange')
```
base1 is almost the same color as the background.
If changed from base1 to something else like base7, the cursor is visible again.

**Comment by whatyouhide** [comment]
Great @fcobos, could you send a PR with the fix and screenshots of how the fix looks like? That would be awesome :D
