### ISSUE TITLE
Python: `return` is almost the same color as comments

### ISSUE THREAD

**Issue by vitaly-zdanevich** [whatyouhide/vim-gotham#51]
![image](https://user-images.githubusercontent.com/3514015/53227658-ef07cd80-368f-11e9-9c06-52328588917d.png)

macOS, Term.app.

**Comment by whatyouhide** [comment]
The colorscheme is designed to be really dark. I think if you have something after the `return` (which I assume most of the time you do) then it should be hard to confuse the `return` for a comment. I'm inclined to leave things like they are now, but thanks for the report!
