### ISSUE TITLE
Is it possible to differentiate between error types

### ISSUE THREAD

**Issue by sittim** [whatyouhide/vim-gotham#60]
I am using NVIM LSP with [LSPSAGA](https://github.com/glepnir/lspsaga.nvim) and here is how the errors and warning are displayed with gotham enabled.

![image](https://user-images.githubusercontent.com/8825037/129707818-de5e2f7f-23f3-40c0-90be-a8fa0c29bb0b.png)

Here is how they are displayed in Nord color scheme.

![image](https://user-images.githubusercontent.com/8825037/129706594-46abcf51-c7aa-412a-bd83-16ba84800d95.png)

I absolutely love vim-gotham, and wanted to ask if there is any way to add little color tints to the error, warning and info icons?

**Comment by whatyouhide** [comment]
Hey @sittim, that's a nice suggestion. I won't have time to look into this. Any chance you could take a look and report back? Thanks in advance! 🤗

**Comment by sittim** [comment]
I will do so, I have never dealt with colorschemes, but will try.

**Comment by sittim** [comment]
It looks like the plugin:

https://github.com/folke/lsp-colors.nvim

should fix this issue.
