### ISSUE TITLE
NeoVim support

### ISSUE THREAD

**Issue by nyngwang** [whatyouhide/vim-gotham#63]
As title. While I haven't tested it. I think the problem is that the support of `nvim-treesitter/nvim-treesitter` is needed.

**update**: OK it doesn't work:

<img src="https://user-images.githubusercontent.com/24765272/167517667-5a2258b2-19de-46d0-8549-a08adef0064d.png" width="500">

**Comment by whatyouhide** [comment]
Hey @nyngwang, thanks for the issue. Are you up for trying to implement support for `nvim-treesetter`? 🙃 I currently have zero time to dedicate to this 😄

**Comment by nyngwang** [comment]
No one wants to save Gotham. Sad.

**Comment by shmerl** [comment]
What exactly is broken? The theme itself works fine with neovim for me.

**Comment by whatyouhide** [comment]
That's good to know. Well we're 1-1, so I'll go with @shmerl and assume it's working (out of laziness!). Feel free to comment down here if you have issues with NeoVim.

**Comment by shmerl** [comment]
If anyone needs, I started the [neogotham theme](https://github.com/shmerl/neogotham) that's focused on neovim support.
