### ISSUE TITLE
Repo readme images look broken

### ISSUE THREAD

**Issue by shmerl** [whatyouhide/vim-gotham#64]
Current images don't show up anymore.

But you can recover them here:

* https://web.archive.org/web/20210123055902/https://camo.githubusercontent.com/8fb9352c94a9e79a651590014ce2edb7a7f490b273cf16480e56e4f8b0d7e17d/687474703a2f2f692e696d6775722e636f6d2f46444c457a48432e706e67

* https://web.archive.org/web/20210123055902/https://camo.githubusercontent.com/c6798129e9cadb8f30e15d4214e9e40fd224f462edf229114fb596ad473529f2/687474703a2f2f692e696d6775722e636f6d2f4e66527548464e2e706e67

**Comment by whatyouhide** [comment]
Ah, great catch! And thanks for including the links. I re-uploaded them, and it's looking good now.
