### ISSUE TITLE
I put to ~/.vim/colors/gotham but `:colorscheme gotham` returns "E185: Cannot find color scheme 'gotham'"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [whatyouhide/vim-gotham#66]

**Comment by whatyouhide** [comment]
Hey @vitaly-zdanevich, thanks for the issue. I haven't used Vim in ~10 years so I’m not even sure about what the ecosystem looks like now. Maybe you're on NeoVim or something. Anyways, I'd ask on some dedicated forum or something similar. Thanks!

**Comment by vitaly-zdanevich** [comment]
Solved by `runtime colors/gotham/colors/gotham256.vim`
