### ISSUE TITLE
Autocompletion: not distingushible current item

### ISSUE THREAD

**Issue by vitaly-zdanevich** [whatyouhide/vim-gotham#67]
![Screenshot 2024-05-04 at 17 29 00](https://github.com/whatyouhide/vim-gotham/assets/3514015/b8aaea45-77f8-4ad7-b902-49114c073bef)

**Comment by whatyouhide** [comment]
@vitaly-zdanevich sorry to hear. This theme has been out there for 10 years so I’m not sure why this was never reported. Either way, I don't even have the setup to test this right now. Feel free to play around with the colors for the current item there and make a PR here, I'll gladly accept contributions, but I don't plan on working on this anytime soon. Cheers! 💟
